config/routes.rb
Rails.application.routes.draw do
  resources :portfolio_one_to_manies
  resources :portfolios
  devise_for :students, controllers: { 
  registrations: 'students/registrations',
  sessions: 'students/sessions',
  passwords: 'students/passwords' 
}
  
  # Necessary Student routes and  portfolio routes
  resources :students, only: [:index, :show, :edit, :update, :destroy] do
    resource :portfolio, only: [:show, :edit, :update]  # Nesting portfolio under student

    resources :projects_to_manies, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "students#index"
end

app/models/portfolio_one_to_many.rb
class PortfolioOneToMany < ApplicationRecord
end

app/controllers/portfolio_one_to_manies_controller.rb
class PortfolioOneToManiesController < ApplicationController
  before_action :set_portfolio_one_to_many, only: %i[ show edit update destroy ]

  # GET /portfolio_one_to_manies or /portfolio_one_to_manies.json
  def index
    @portfolio_one_to_manies = PortfolioOneToMany.all
  end

  # GET /portfolio_one_to_manies/1 or /portfolio_one_to_manies/1.json
  def show
  end

  # GET /portfolio_one_to_manies/new
  def new
    @portfolio_one_to_many = PortfolioOneToMany.new
  end

  # GET /portfolio_one_to_manies/1/edit
  def edit
  end

  # POST /portfolio_one_to_manies or /portfolio_one_to_manies.json
  def create
    @portfolio_one_to_many = PortfolioOneToMany.new(portfolio_one_to_many_params)

    respond_to do |format|
      if @portfolio_one_to_many.save
        format.html { redirect_to portfolio_one_to_many_url(@portfolio_one_to_many), notice: "Portfolio one to many was successfully created." }
        format.json { render :show, status: :created, location: @portfolio_one_to_many }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @portfolio_one_to_many.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolio_one_to_manies/1 or /portfolio_one_to_manies/1.json
  def update
    respond_to do |format|
      if @portfolio_one_to_many.update(portfolio_one_to_many_params)
        format.html { redirect_to portfolio_one_to_many_url(@portfolio_one_to_many), notice: "Portfolio one to many was successfully updated." }
        format.json { render :show, status: :ok, location: @portfolio_one_to_many }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @portfolio_one_to_many.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolio_one_to_manies/1 or /portfolio_one_to_manies/1.json
  def destroy
    @portfolio_one_to_many.destroy!

    respond_to do |format|
      format.html { redirect_to portfolio_one_to_manies_url, notice: "Portfolio one to many was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio_one_to_many
      @portfolio_one_to_many = PortfolioOneToMany.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def portfolio_one_to_many_params
      params.fetch(:portfolio_one_to_many, {})
    end
end

app/helpers/portfolio_one_to_manies_helper.rb
module PortfolioOneToManiesHelper
end

app/views/portfolio_one_to_manies/_form.html.erb
<%= form_with(model: portfolio_one_to_many) do |form| %>
  <% if portfolio_one_to_many.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(portfolio_one_to_many.errors.count, "error") %> prohibited this portfolio_one_to_many from being saved:</h2>

      <ul>
        <% portfolio_one_to_many.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolio_one_to_manies/_portfolio_one_to_many.html.erb
<div id="<%= dom_id portfolio_one_to_many %>">
</div>

app/views/portfolio_one_to_manies/edit.html.erb
<h1>Editing portfolio one to many</h1>

<%= render "form", portfolio_one_to_many: @portfolio_one_to_many %>

<br>

<div>
  <%= link_to "Show this portfolio one to many", @portfolio_one_to_many %> |
  <%= link_to "Back to portfolio one to manies", portfolio_one_to_manies_path %>
</div>

app/views/portfolio_one_to_manies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Portfolio one to manies</h1>

<div id="portfolio_one_to_manies">
  <% @portfolio_one_to_manies.each do |portfolio_one_to_many| %>
    <%= render portfolio_one_to_many %>
    <p>
      <%= link_to "Show this portfolio one to many", portfolio_one_to_many %>
    </p>
  <% end %>
</div>

<%= link_to "New portfolio one to many", new_portfolio_one_to_many_path %>

app/views/portfolio_one_to_manies/new.html.erb
<h1>New portfolio one to many</h1>

<%= render "form", portfolio_one_to_many: @portfolio_one_to_many %>

<br>

<div>
  <%= link_to "Back to portfolio one to manies", portfolio_one_to_manies_path %>
</div>

app/views/portfolio_one_to_manies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @portfolio_one_to_many %>

<div>
  <%= link_to "Edit this portfolio one to many", edit_portfolio_one_to_many_path(@portfolio_one_to_many) %> |
  <%= link_to "Back to portfolio one to manies", portfolio_one_to_manies_path %>

  <%= button_to "Destroy this portfolio one to many", @portfolio_one_to_many, method: :delete %>
</div>